### PR TITLE
Various bugfixes to handle applications that use ember-auto-import 

### LINKED ISSUE #41: Ember Server failing on test-support.js on v1.2.4
On v1.2.3, `ember server` would successfully complete (though the application wouldn't run).

Now on v1.2.4 `ember server` errors out with the following message

```
Build Error (RequireFilter) in assets/test-support.js

Cannot read property 'length' of undefined

ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: Cannot read property 'length' of undefined
    at new Scanner (/home/ggayowsky/Workbench/DIRECT/rspace/node_modules/esprima/dist/esprima.js:5141:29)
    at new Parser (/home/ggayowsky/Workbench/DIRECT/rspace/node_modules/esprima/dist/esprima.js:1851:25)
    at parse (/home/ggayowsky/Workbench/DIRECT/rspace/node_modules/esprima/dist/esprima.js:120:19)
    at Object.parseScript (/home/ggayowsky/Workbench/DIRECT/rspace/node_modules/esprima/dist/esprima.js:145:13)
    at replaceRequireAndDefine (/home/ggayowsky/Workbench/DIRECT/rspace/node_modules/ember-cli-amd/index.js:443:23)
    at /home/ggayowsky/Workbench/DIRECT/rspace/node_modules/ember-cli-amd/index.js:499:33
    at walk (/home/ggayowsky/Workbench/DIRECT/rspace/node_modules/esprima-walk/esprima-walk.js:12:3)
    at replaceRequireAndDefine (/home/ggayowsky/Workbench/DIRECT/rspace/node_modules/ember-cli-amd/index.js:451:3)
    at /home/ggayowsky/Workbench/DIRECT/rspace/node_modules/ember-cli-amd/index.js:499:33
    at walk (/home/ggayowsky/Workbench/DIRECT/rspace/node_modules/esprima-walk/esprima-walk.js:12:3)
  - codeFrame: Cannot read property 'length' of undefined
  - errorMessage: assets/test-support.js: Cannot read property 'length' of undefined
        in /tmp/broccoli-1643pIf0FdkyAuGn/out-186-append_ember_auto_import_analyzer
        at RequireFilter
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: assets/test-support.js
    - line: [undefined]
    - treeDir: /tmp/broccoli-1643pIf0FdkyAuGn/out-186-append_ember_auto_import_analyzer
  - message: assets/test-support.js: Cannot read property 'length' of undefined
        in /tmp/broccoli-1643pIf0FdkyAuGn/out-186-append_ember_auto_import_analyzer
        at RequireFilter
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: RequireFilter
  - originalErrorMessage: Cannot read property 'length' of undefined
  - stack: TypeError: Cannot read property 'length' of undefined
    at new Scanner (/home/ggayowsky/Workbench/DIRECT/rspace/node_modules/esprima/dist/esprima.js:5141:29)
    at new Parser (/home/ggayowsky/Workbench/DIRECT/rspace/node_modules/esprima/dist/esprima.js:1851:25)
    at parse (/home/ggayowsky/Workbench/DIRECT/rspace/node_modules/esprima/dist/esprima.js:120:19)
    at Object.parseScript (/home/ggayowsky/Workbench/DIRECT/rspace/node_modules/esprima/dist/esprima.js:145:13)
    at replaceRequireAndDefine (/home/ggayowsky/Workbench/DIRECT/rspace/node_modules/ember-cli-amd/index.js:443:23)
    at /home/ggayowsky/Workbench/DIRECT/rspace/node_modules/ember-cli-amd/index.js:499:33
    at walk (/home/ggayowsky/Workbench/DIRECT/rspace/node_modules/esprima-walk/esprima-walk.js:12:3)
    at replaceRequireAndDefine (/home/ggayowsky/Workbench/DIRECT/rspace/node_modules/ember-cli-amd/index.js:451:3)
    at /home/ggayowsky/Workbench/DIRECT/rspace/node_modules/ember-cli-amd/index.js:499:33
    at walk (/home/ggayowsky/Workbench/DIRECT/rspace/node_modules/esprima-walk/esprima-walk.js:12:3)

=================================================================================
```

Here is my projects package.json dependencies

  "devDependencies": {
    "@ember/jquery": "^0.5.2",
    "@ember/optional-features": "^0.6.3",
    "broccoli-asset-rev": "^2.7.0",
    "ember-auto-import": "^1.2.10",
    "ember-cli": "~3.7.1",
    "ember-cli-amd": "1.2.4",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "^7.1.2",
    "ember-cli-cjs-transform": "^1.3.0",
    "ember-cli-content-security-policy": "^1.0.0",
    "ember-cli-dependency-checker": "^3.0.0",
    "ember-cli-eslint": "^4.2.3",
    "ember-cli-htmlbars": "^3.0.0",
    "ember-cli-htmlbars-inline-precompile": "^1.0.3",
    "ember-cli-inject-live-reload": "^1.8.2",
    "ember-cli-sass": "^8.0.1",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-uglify": "^2.1.0",
    "ember-component-css": "^0.6.5",
    "ember-concurrency": "^0.8.26",
    "ember-export-application-global": "^2.0.0",
    "ember-fetch": "^5.1.3",
    "ember-load-initializers": "^1.1.0",
    "ember-qunit": "^3.4.1",
    "ember-resolver": "^5.0.1",
    "ember-source": "~3.7.0",
    "ember-truth-helpers": "^2.0.0",
    "eslint": "^5.7.0",
    "eslint-config-semistandard": "^12.0.1",
    "eslint-config-standard": "^11.0.0",
    "eslint-plugin-ember": "^5.2.0",
    "eslint-plugin-header": "^1.2.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-node": "^7.0.1",
    "eslint-plugin-promise": "^4.0.0",
    "eslint-plugin-standard": "^3.0.1",
    "glob": "^4.5.3",
    "http-proxy": "^1.17.0",
    "loader.js": "^4.7.0",
    "morgan": "^1.9.0",
    "sass": "^1.14.3",
    "sinon": "^7.0.0"
  },
  "engines": {
    "node": "6.* || 8.* || >= 10.*"
  },
  "dependencies": {
    "d3": "^5.7.0",
    "d3-scale-chromatic": "^1.3.3",
    "font-awesome": "^4.7.0",
    "jquery-ui-dist": "^1.12.1",
    "jquery-ui-touch-punch": "^0.2.3",
    "moment": "^2.22.2",
    "normalize.css": "^3.0.3",
    "nouislider": "^11.1.0",
    "spin.js": "^3.1.0",
    "tinycolor2": "^1.4.1"
  }

### PR DESCRIPTION
**Pull request by ggayowsky**
This PR fixes #41 as well as other problems with replacing require and define in the ember-auto-import webpack evals.

 - Fixed an issue in the replace logic for the webpack eval code that was trying to parse arguments passed to eval that were not string literals.
- Fixed an issue where only newline characters were getting escaped in the modified webpack eval code. (Now all special characters should be replaced)
- Fixed an issue where the modified webpack eval code was a different length than the unmodified code. This could cause any file that had ember-auto-import code (vendor.js, test-support.js, etc.) to be malformed. Modify the write function to handle this case.

### CODE REVIEW

**Comment by ggayowsky** [comment]
@ffaubry or any other maintainer of this repostiory. Our applcation and potentially anybody else using ember-auto-import are blocked from using version 2.x.x until these bugfixes are integrated.

In our case `moment.js` being used in the application, and `sinon` being used in the tests were causing these issue.

Would appreciate a review and new release as soon as possible.

File: index.js [hunk 1]
```diff
@@ -299,9 +299,10 @@ RequireFilter.prototype.processString = function(code) {
   return replaceRequireAndDefine(code, this.amdPackages, this.amdModules);
 };
 
-function write(arr, str, offset) {
-  for (var i = 0, l = str.length; i < l; i++) {
-    arr[offset + i] = str[i];
+function write(arr, str, offset, len) {
+  arr[offset] = str;
+  for (let i = 1; i < len; i++) {
+    arr[offset + i] = undefined;
```
Comment (ffaubry) [inline index.js]: I think the loop is wrong.
Is your intention to fill up the remaining of the space with `undefined`?
What you seem to try to do is:
- copy the `str` into the array at the `offset`
- then fill the *rest* with undefined
If this is true then the for loop should start at `str.lengh`
Add a comment to explain what you are trying to do.

File: index.js [hunk 2]
```diff
@@ -363,11 +364,11 @@ function replaceRequireAndDefine(code, amdPackages, amdModules) {
         }
 
         // Dealing with ember-auto-import eval
-        if (node.callee.name === 'eval') {
+        if (node.callee.name === 'eval' && node.arguments[0].type === 'Literal' && typeof node.arguments[0].value === 'string') {
           const evalCode = node.arguments[0].value;
           const evalCodeAfter = replaceRequireAndDefine(evalCode, amdPackages, amdModules);
           if (evalCode !== evalCodeAfter) {
-            write(buffer, "eval(\"" + evalCodeAfter.replace(/\n/g, "\\n") + "\");", node.range[0]);
+            write(buffer, "eval(" + JSON.stringify(evalCodeAfter) + ");", node.range[0], node.range[1] - node.range[0]);
```
Comment (ffaubry) [inline index.js]: Are you sure about this?
Don't we need the double quote around the string?
`eval("....");`

**Comment by ffaubry** [comment]
@ggayowsky Thx for addressing this.

File: index.js (hunk 2 above)
Comment (ggayowsky) [reply index.js]: 100% sure they are not needed. Tested in my application.

Idea gotten for here
https://stackoverflow.com/questions/21672334/javascript-how-to-show-escape-characters-in-a-string

Comment (ffaubry) [reply index.js]: Yep you are right.

File: index.js (hunk 1 above)
Comment (ggayowsky) [reply index.js]: The loop is correct.

The idea is that before this function is called, the original unmodified code is stored between `offset` (range[0]) and `offset + len` (range[1]).

We need to fit the modified code into the same range. If the buffer size is changed, the remaining node.range from the ast are out of sync with the buffer... and it would be tricky to keep track of how things shifted.

So my little "hack" is the putting the entire string into the offset position, then fill the remaining characters in the original unmodified code range with undefined (node.range[0] + 1, node.range[1]). Since we are really just using `buffer.join('')` at the end. This works.

Here is an example:
```
const buffer = ['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd'].
```
Let's say we want to replace "Hello" with "Goodnight"

In this case, `node.range = [0, 5]`, `str = "Goodnight"`.

So offset = node.range[0] = 0, len = 5

Using my method, the buffer becomes:
```
buffer = ['Goodnight', undefined, undefined, undefined, undefined, ' ', 'W', 'o', 'r', 'l', 'd']
```

Using you suggestion it would become:
```
buffer = ['Goodnight', undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, 'l', 'd'];
```
which is not what we want.
```


I thought about actually just passing the range object to this function.
So it would look like:
```
function write(arr, str, range) {
  const offset = range[0];
  arr[offset] = str;
  for (let i = 1; i < range[1]; i++) {
    arr[offset + i] = undefined;
  }
}
```

Let me know if you prefer my alternative. I will also leave a comment

Comment (ggayowsky) [reply index.js]: Hopefully my explanation above helped you understand the logic.

Also, updated the write signature and added a comment explaining the write function "hack"

Comment (ffaubry) [reply index.js]: OK. Now I understand what you are doing. 
Pretty cool/smart.

Is this working in your app?

**Comment by ffaubry** [comment]
Update the change log as well.

File: index.js (hunk 1 above)
Comment (ggayowsky) [reply index.js]: Yes. Everything here has been tested against my application!

**Comment by ffaubry** [comment]
Pretty cool/smart.

Is this working in your app?

Update the change log as well.

**Comment by ggayowsky** [comment]
Everything was tested against my app and I finally got the application with v2.x.x and my changes.

I can update the changelog... I am guessing the next version will be 2.0.2?

File: index.js [hunk 3]
```diff
@@ -363,11 +373,11 @@ function replaceRequireAndDefine(code, amdPackages, amdModules) {
         }
 
         // Dealing with ember-auto-import eval
-        if (node.callee.name === 'eval') {
+        if (node.callee.name === 'eval' && node.arguments[0].type === 'Literal' && typeof node.arguments[0].value === 'string') {
```
Comment (ffaubry) [inline index.js]: What's the scenario that lead you to add these extra tests?

Comment (ggayowsky) [reply index.js]: Cases where the eval string is stored in a variable.

In my case, from `sinon-esm.js`
```
function callTimer(clock, timer) {
    ...
    /* eslint no-eval: "off" */
    eval(timer.func);
    ...
}
```

`node.arguments[0].value` was null. So trying to pass value to `replaceRequireAndDefine` ended poorly

Comment (ffaubry) [reply index.js]: Thx

Comment (ggayowsky) [reply index.js]: And changelog added.

**Comment by ffaubry** [comment]
Thx Gerald for stepping in and helping.
We appreciate.
